filetype off
filetype plugin indent on

"Set mapleader
let mapleader = ","
let g:mapleader = ","

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" This means that you can have unwritten changes to a file and open a new file using :e,
" without being forced to write or undo your changes first.
" Also, undo buffers and marks are preserved while the buffer is open.
" This is an absolute must-have
set hidden

" Also, I like Vim to have a large undo buffer, a large history of commands,
" ignore some file extensions when completing names by pressing Tab,
" and be silent about invalid cursor moves and other errors.
set history=1000 " remember more commands and search history
set wildignore=*.swp,*.bak,*.pyc,*.class
set title " change the terminal's title
set visualbell " don't beep
set noerrorbells " don't beep

set undodir=~/.vim/undodir
set undofile
set undolevels=1000 "maximum number of changes that can be undone
set undoreload=10000 "maximum number lines to save for undo on a buffer reload

set ruler "pour afficher la ligne/colonne en bas

"set colorcolumn=80,120 "red column

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" It clears the search buffer when you press ,/
" (Tired of clearing highlighted searches by searching for “ldsfhjkhgakjks")
nmap <silent> <leader>/ :nohlsearch<CR>
nmap <silent> <leader>> :%s#\s*\r\?$##<CR>:nohlsearch<CR>

" This lets you use w!! to do that after you opened the file that requires root privileges
cmap w!! w !sudo tee % >/dev/null


set whichwrap=b,s,<,>,[,]
syntax enable
colo desert
set nu
set guifont=ProggyCleanTT:h12
set hls
set guioptions-=T "get rid of toolbar
filetype plugin on
set smartindent
set autoindent
set expandtab
set list
set cursorline
set hidden
set listchars=tab:>-,trail:.,nbsp:+
se et ts=8 sw=4 softtabstop=4 smarttab
au BufEnter *.py set sw=4 sts=4 ts=4 et sta ai
nnoremap <silent> <C-N> :bn<CR>
nnoremap <silent> <C-P> :bp<CR>
map <F2> :NERDTreeToggle<CR>
map <F5> :cd %:h<CR>:!EditionC mode(MultiLeafEnhancement) ScriptFileName(%) MachineID(1) Resolution(300)
"map <F3> :!\\Fileserver_a\development\TagG-Informatique\DocumentEdition\Preview\Preview.exe %<CR>
"map <F5> :!gnome-terminal -e "python2.6 -m pdb %"<CR><CR>
"map <F6> :!xterm -hold -e "python2.6 -m pdb % -v"<CR><CR>
nnoremap <F7> :GundoToggle<CR>
map <F9> :%!xxd<CR>
map <F10> :%!xxd -r<CR>
map <F12> :Align 

let NERDTreeIgnore=['\.pyo$', '\~$']

let g:Tb_MaxSize = 40
let g:Tb_VSplit = 40
let g:Tb_MoreThanOne = 1

" to avoid doing ctrl+c or ESC to exit insert mode
inoremap jj <ESC>

let g:delimitMate_apostrophes = ''

au BufRead,BufNewFile *.apa		set filetype=apa

set bs=2 "pour le backspace
